# Generated by Django 2.1.5 on 2023-10-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
