# Generated by Django 2.1.5 on 2023-10-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_person_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='bio',
            new_name='Texto',
        ),
        migrations.AlterField(
            model_name='person',
            name='IP',
            field=models.CharField(max_length=30),
        ),
    ]
